spring.application.name=APPOINTMENT-SERVICE

# Isse service khud ko register bhi karegi aur baki services ka data fetch bhi karegi
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Server Port (Ensure karo baki MS se alag ho, jaise 8086)
server.port=8085

# Database Connection Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_appointment
spring.datasource.username=postgres
spring.datasource.password=aman

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Server ka main address jahan report karni hai
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.config.enabled=false