spring.application.name=INTERNAL-EMAIL-SERVICE

# Server Port (Ensure karo yeh baki MS se alag ho, jaise 8085)
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_email
spring.datasource.username=postgres
spring.datasource.password=xxxx

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Isse service khud ko register bhi karegi aur baki services ka data fetch bhi karegi
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka Server ka main address jahan report karni hai
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
