# 1. Server & Application Name
server.port=8081
spring.application.name=AUTH-EMPLOYEE-SERVICE

# 2. PostgreSQL Database Connection (pgAdmin se matching)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_employee
spring.datasource.username=postgres
spring.datasource.password=xxxx
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Eureka Client Registration (Ab ise true kar diya hai)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
