# Server Port (Ensure karo baki MS se alag ho, jaise 8086)
server.port=8084

# Spring Application Name
spring.application.name=VIDEO-MEETING-SERVICE

# Database Connection Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/video_meeting
spring.datasource.username=postgres
spring.datasource.password=xxxx

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Isse service khud ko register bhi karegi aur baki services ka data fetch bhi karegi
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka Server ka main address jahan report karni hai
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
