# Server Port (Standard Eureka Port)
server.port=8761
spring.application.name=EUREKA-SERVER

# Kyunki yeh khud hi server hai, isliye yeh khud ko hi register ya fetch nahi karega
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
